# Generated by Django 4.1.13 on 2024-02-25 14:02

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectdetails_search_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='description',
            field=wagtail.fields.RichTextField(),
        ),
    ]
