# Generated by Django 4.1.13 on 2024-02-23 14:19

import contact.models
from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0002_alter_genericpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock(form_classname='container')), ('contact', contact.models.ContactBlock())], use_json_field=True),
        ),
    ]
