# Generated by Django 4.1.13 on 2024-02-25 14:02

import contact.models
from django.db import migrations
import wagtail.blocks
import wagtail.images.blocks
import website.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0003_alter_genericpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='body',
            field=website.blocks.WebsiteBlockField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock(form_classname='container')), ('contact', contact.models.ContactBlock()), ('hero_caraousel', wagtail.blocks.StructBlock([('items', wagtail.blocks.ListBlock(website.blocks.HeroCaraouselBlock.HeroItemBlock))])), ('feature', wagtail.blocks.StructBlock([('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))]), max_num=4))])), ('about', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('sub_title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.RichTextBlock(required=True)), ('button_text', wagtail.blocks.CharBlock(default='Learn More', required=False)), ('button_link', wagtail.blocks.PageChooserBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_position', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right')]))])), ('project_list', website.blocks.ProjectListBlock()), ('video', wagtail.blocks.StructBlock([('video_url', wagtail.blocks.URLBlock(required=True))])), ('faq', wagtail.blocks.StructBlock([('faqs', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('question', wagtail.blocks.CharBlock(required=True)), ('answer', wagtail.blocks.TextBlock(required=True))]), min_num=2))])), ('fact', wagtail.blocks.StructBlock([('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('number', wagtail.blocks.CharBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))]), max_num=4, min_num=4))])), ('team', wagtail.blocks.StructBlock([('sub_title', wagtail.blocks.CharBlock(required=False)), ('title', wagtail.blocks.CharBlock(required=True)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(required=True)), ('position', wagtail.blocks.CharBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('socials', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(required=True)), ('url', wagtail.blocks.URLBlock(required=True)), ('icon', wagtail.blocks.CharBlock(help_text='Font Awesome 5 icon', required=True))])))])))])), ('testimonial', wagtail.blocks.StructBlock([('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock(required=True)), ('name', wagtail.blocks.CharBlock(required=True)), ('position', wagtail.blocks.CharBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))])))]))], use_json_field=True),
        ),
    ]
