# Generated by Django 4.1.13 on 2024-02-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_socialmediasettings_homepage_body_genericsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReCaptchaSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RECAPTCHA_PUBLIC_KEY', models.CharField(blank=True, max_length=255, null=True)),
                ('RECAPTCHA_PRIVATE_KEY', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
